/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baru;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abet
 */
public class DATAOBAT extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    
    public Statement st;
    public ResultSet rs;
    private String tgl;
    private String kombo;
    Connection cn = Koneksi.koneksi_database.BukaKoneksi();
    
    public DATAOBAT() {
        initComponents();
        TampilData();
    }
    
     private void bersih(){
   
        txtID.setText("");
        txtNAMA.setText("");
        txtHARGA.setText("");
        txtHARGA.setText("");
        txtDATE.setDate(null);
        txtSTOCK.setText("");
        
        btnSIMPAN.setText("SIMPAN");
    }
     
         private void TampilData(){
try{
    st = cn.createStatement();
    rs = st.executeQuery("SELECT * FROM dataobat");
    
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No.");
    model.addColumn("ID");
    model.addColumn("NAMA");
    model.addColumn("HARGA");
    model.addColumn("TGL_EXP");
    model.addColumn("STOCK");
    model.addColumn("JENIS");
    
    int no = 1;
    model.getDataVector().removeAllElements();
    model.fireTableDataChanged();
    model.setRowCount(0);
    
    while (rs.next()){
        Object[] data ={
            no++,
            rs.getString("ID"),
            rs.getString("NAMA"),
            rs.getString("HARGA"),
            rs.getString("TGL_EXP"),
            rs.getString("STOCK"),
            rs.getString("JENIS")};
            
            model.addRow(data);
            tblDATA.setModel(model);
        }
      
}
    catch(Exception e){}
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNAMA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtSTOCK = new javax.swing.JTextField();
        txtHARGA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtJENIS = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSIMPAN = new javax.swing.JButton();
        txtMENUUTAMA = new javax.swing.JButton();
        btnBATAL = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnDELETE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDATA = new javax.swing.JTable();
        txtDATE = new com.toedter.calendar.JDateChooser();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 440));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 148, 68));
        jLabel3.setText("ID OBAT");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 148, 68));
        jLabel4.setText("NAMA OBAT");

        txtSTOCK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSTOCKActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 148, 68));
        jLabel5.setText("HARGA OBAT");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 148, 68));
        jLabel6.setText("STOCK OBAT");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 148, 68));
        jLabel8.setText("TANGGAL EXPIRED");

        txtJENIS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TABLET", "KAPSUL", "SIRUP" }));
        txtJENIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJENISActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 148, 68));
        jLabel10.setText("JENIS OBAT");

        jPanel2.setBackground(new java.awt.Color(0, 148, 68));

        btnSIMPAN.setText("SIMPAN");
        btnSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSIMPANActionPerformed(evt);
            }
        });

        txtMENUUTAMA.setText("MENU UTAMA");
        txtMENUUTAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMENUUTAMAActionPerformed(evt);
            }
        });

        btnBATAL.setText("BATAL");
        btnBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBATALActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DATA OBAT");

        btnDELETE.setBackground(new java.awt.Color(255, 102, 102));
        btnDELETE.setForeground(new java.awt.Color(255, 255, 255));
        btnDELETE.setText("HAPUS");
        btnDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDELETE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBATAL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMENUUTAMA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSIMPAN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(btnSIMPAN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBATAL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(txtMENUUTAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        tblDATA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAMA", "HARGA", "TGL_EXP", "STOCK", "JENIS"
            }
        ));
        tblDATA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDATAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDATA);

        txtDATE.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtDATEPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(txtID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtHARGA, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSTOCK, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJENIS, 0, 204, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(txtDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHARGA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSTOCK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJENIS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 440));

        setSize(new java.awt.Dimension(921, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSTOCKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSTOCKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSTOCKActionPerformed

    private void txtMENUUTAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMENUUTAMAActionPerformed
        new MENUUTAMA().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtMENUUTAMAActionPerformed

    private void btnSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSIMPANActionPerformed
        // TODO add your handling code here:
                try{
            st = cn.createStatement();
            if(txtID.getText().equals("") || 
                    txtNAMA.getText().equals("") ||
                    txtHARGA.getText().equals("") ||
                    txtSTOCK.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong","Validasi Data",JOptionPane.INFORMATION_MESSAGE);
                return;
        }
            if(btnSIMPAN.getText()== "SIMPAN"){
                String cek = "SELECT * FROM dataobat WHERE ID = '" + txtID.getText() + "'";
                rs = st.executeQuery(cek);
                
                if (rs.next()){
                    JOptionPane.showMessageDialog(null,"Ups..ID ini sudah ada");
                    
                }else{
                    
                String sql = "INSERT INTO dataobat VALUES ('" + txtID.getText() + "','" + txtNAMA.getText() + "','" + txtHARGA.getText() + "','" + tgl+ "','" + txtSTOCK.getText() + "','" + kombo + "')";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
                bersih();
                TampilData();
                        }
            }else{
            String update =  "UPDATE dataobat SET NAMA = '" + txtNAMA.getText() +
                    "', HARGA = '" + txtHARGA.getText() + 
                    "', TGL_EXP = '" + tgl + 
                    "',STOCK = '" + txtSTOCK.getText() + 
                    "',JENIS = '" + kombo + 
                    "' WHERE ID = '" + txtID.getText() + "'";
            st.executeUpdate(update); 
            JOptionPane.showMessageDialog(null, "Data berhasil Disimpan");
                bersih();
                TampilData();
                
            }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,e );
        }
    }//GEN-LAST:event_btnSIMPANActionPerformed

    private void txtDATEPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtDATEPropertyChange
        // TODO add your handling code here:
           if(txtDATE.getDate()!=null){   
       SimpleDateFormat format_tanggal = new SimpleDateFormat("yyyy-MM-dd");
   tgl = format_tanggal.format(txtDATE.getDate());
   } 
    }//GEN-LAST:event_txtDATEPropertyChange

    private void txtJENISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJENISActionPerformed
        // TODO add your handling code here:
        kombo = txtJENIS.getSelectedItem().toString();  
    }//GEN-LAST:event_txtJENISActionPerformed

    private void tblDATAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDATAMouseClicked
        // TODO add your handling code here:
        txtID.setText(tblDATA.getValueAt(tblDATA.getSelectedRow(),1).toString());
txtNAMA.setText(tblDATA.getValueAt(tblDATA.getSelectedRow(),2).toString());
txtHARGA.setText(tblDATA.getValueAt(tblDATA.getSelectedRow(),3).toString());
String dateString = tblDATA.getValueAt(tblDATA.getSelectedRow(),4).toString();
txtSTOCK.setText(tblDATA.getValueAt(tblDATA.getSelectedRow(),5).toString());
String jenisString = tblDATA.getValueAt(tblDATA.getSelectedRow(),6).toString();


SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
try {
        Date date = dateFormat.parse(dateString);
        txtDATE.setDate(date);
    } catch (ParseException e) {}
// TODO add your handling code here:

btnSIMPAN.setText("Ubah");
    }//GEN-LAST:event_tblDATAMouseClicked

    private void btnDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEActionPerformed
        // TODO add your handling code here:
        if(txtID.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Silahkan Pilih Data yang akan dihapus !");
        }else{
            int jawab = JOptionPane.showConfirmDialog(null, "Data Ini akan dihapus,Lanjutkan?","Konfirmasi",JOptionPane.YES_NO_OPTION );
            if (jawab == 0){
                try {
                    st = cn.createStatement();
                    String sql = "DELETE FROM dataobat WHERE ID = '" + txtID.getText() +"'";
                    st.execute(sql);                    
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    bersih();
                    TampilData();
                   
                    
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
            }
        }
    }//GEN-LAST:event_btnDELETEActionPerformed

    private void btnBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBATALActionPerformed
        // TODO add your handling code here:
        bersih(); 
    }//GEN-LAST:event_btnBATALActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DATAOBAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DATAOBAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DATAOBAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DATAOBAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DATAOBAT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBATAL;
    private javax.swing.JButton btnDELETE;
    private javax.swing.JButton btnSIMPAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDATA;
    private com.toedter.calendar.JDateChooser txtDATE;
    private javax.swing.JTextField txtHARGA;
    private javax.swing.JTextField txtID;
    private javax.swing.JComboBox<String> txtJENIS;
    private javax.swing.JButton txtMENUUTAMA;
    private javax.swing.JTextField txtNAMA;
    private javax.swing.JTextField txtSTOCK;
    // End of variables declaration//GEN-END:variables
}
